# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "540d2178130770d2fa72da8461f0de90"
name = "loyalty-dashboard"
handle = "loyalty-dashboard"
application_url = "https://essential-anymore-manually-recovered.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dershil-demo.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_orders,read_price_rules,read_products,write_discounts,write_orders,write_price_rules,write_products"

[auth]
redirect_urls = [
  "https://essential-anymore-manually-recovered.trycloudflare.com/auth/callback",
  "https://essential-anymore-manually-recovered.trycloudflare.com/auth/shopify/callback",
  "https://essential-anymore-manually-recovered.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled", "orders/create" ]
  uri = "https://9offq7b4x6.execute-api.us-east-2.amazonaws.com/v1/shopify/webhook"

[pos]
embedded = false
